[package]
name = "docker-compose"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]

[lib]
test = false

[[test]]
name = "test"
path = "tests/test.rs"
harness = false

[dependencies]
log = "0.3"
serde = "0.7"
serde_json = "0.7"

[dev-dependencies]
env_logger = "0.3"
